### ISSUE TITLE
Refactor argument parsing to allow for clearer errors

### ISSUE THREAD

**Issue by alexomics** [hoffmangroup/pdfcomments#10]
Currently the [`parse_args`](https://github.com/hoffmangroup/pdfcomments/blob/master/pdfcomments/__main__.py#L120-#L133) function returns a `Namespace` of parsed args. I am proposing that `parse_args` instead returns the `ArgumentParser` as this has methods specifically for exiting the program, see [exit methods](https://docs.python.org/3/library/argparse.html#exiting-methods).

`parse_args` would become `get_parser`:
```python
def get_parser() -> argparse.ArgumentParser:
    description = __doc__.splitlines()[0].partition(": ")[2]
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("infile", help="input PDF file")
    parser.add_argument("outfile", nargs="?",
                        help="output text file"
                        " (default: infile with extension changed to 'txt')")

    version = f"%(prog)s {__version__}"
    parser.add_argument("--version", action="version", version=version)

    return parser
```

This would then allow termination to be handled using `ArgumentParser.exit` or `ArgumentParser.error` e.g.:
```python
def main(argv=None):
    parser = get_parser()
    args = parser.parse_args()
    try:
        pdf = PdfFileReader(args.infile)
    except PdfReadError as err:
        parser.error(f"{err}")
        # or: parser.exit(status=2, message=f"{err}\n")
```
Either `exit` or `error` output only the message when called instead of a traceback. `exit` allows setting the status code, `error` always uses status code 2.

**Comment by michaelmhoffman** [comment]
These `argparse` methods are designed for exiting and erroring in the context of argument parsing. I don't think passing them around like this is a good design. And I try to reserve exit status 2 for command-line syntax errors, using a common convention.

If you want shorter error messages for common conditions, use `sys.exit(msg)` but have it much closer to where the exception is thrown.
