### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by agitter** [hoffmangroup/pdfcomments#2]
Amazing tool!  Version 0.1 doesn't run on Windows 😢  [`EX_OK`](https://docs.python.org/3.7/library/os.html#os.EX_OK) cannot be imported from `os` on Windows.

Rather than make it Windows compatible, you could add Linux as a prerequisite in the readme.

**Comment by michaelmhoffman** [comment]
I just run it on WSL. If this is the only thing that's necessary to make this Win32 Python compatible I would be happy to consider this a bug and would accept a pull request along these lines:

```python
try:
    from os import EX_OK
except ImportError:
    EX_OK = 0
```

if someone who cares :wink: can actually test that it works.

Would also accept a pull request that adds Windows or Mac testing to the GitHub Action for a pull request/push.
